export const recyclingCenters = [
  {
    id: "rc-001",
    name: "EcoPlast Recycling Center",
    address: "123 Sustainability Road",
    city: "Nairobi",
    location: { lat: -1.286389, lng: 36.817223 },
    phone: "+254 712 345 678",
    email: "info@ecoplast.co.ke",
    hours: "Mon-Fri: 8am-5pm, Sat: 9am-2pm",
    rating: 4.7,
    distance: 2.3,
    image: "/recycling-facility.png",
    isPartner: true,
    acceptedMaterials: ["PET", "HDPE", "PP", "LDPE"],
    acceptedMaterialsDetails: [
      {
        type: "PET (Polyethylene Terephthalate)",
        code: "Type 1",
        description: "Clear, tough, and solvent resistant. Used for water and soft drink bottles.",
        examples: "Water bottles, soda bottles, cooking oil containers",
      },
      {
        type: "HDPE (High-Density Polyethylene)",
        code: "Type 2",
        description: "Stiff, strong, resistant to chemicals and moisture.",
        examples: "Milk jugs, detergent bottles, shampoo bottles",
      },
      {
        type: "PP (Polypropylene)",
        code: "Type 5",
        description: "Strong, heat resistant, and chemical resistant.",
        examples: "Yogurt containers, medicine bottles, bottle caps",
      },
      {
        type: "LDPE (Low-Density Polyethylene)",
        code: "Type 4",
        description: "Flexible, transparent, and moisture resistant.",
        examples: "Plastic bags, squeeze bottles, food packaging film",
      },
    ],
    preparationGuidelines: [
      "Empty and rinse all containers to remove food residue",
      "Remove all caps, lids, and labels if possible",
      "Flatten bottles and containers to save space",
      "Separate different types of plastic if you can identify them",
      "Avoid bringing plastic bags unless specifically accepted",
    ],
    description:
      "EcoPlast Recycling Center is a state-of-the-art facility dedicated to processing plastic waste into valuable resources. We work with communities, businesses, and individuals to reduce plastic pollution and promote a circular economy.",
    established: "2015",
    capacity: 120,
    facilitySize: 5000,
    collectionRadius: 25,
    satisfactionRate: 92,
    services: [
      "Drop-off recycling for individuals",
      "Commercial waste collection",
      "Plastic processing and transformation",
      "Educational tours and workshops",
      "Recycling consultancy for businesses",
      "Community collection events",
    ],
    certifications: [
      "ISO 14001 Environmental Management",
      "Green Business Certified",
      "Sustainable Recycling Industries (SRI)",
      "Zero Waste to Landfill",
    ],
    directions:
      "Located 2 km from the city center. Take Main Street north, turn right on Sustainability Road. The facility is on the left side with a large green sign.",
    reviews: [
      {
        id: "rev-001",
        userName: "John Kamau",
        userAvatar: "/user-avatar-1.jpg",
        rating: 5,
        date: "2023-09-15T10:30:00",
        comment:
          "Excellent facility! Very organized and staff are helpful. They made it easy to drop off my plastic waste and even gave me tips on how to better sort my recyclables at home.",
        helpfulCount: 12,
        verifiedVisit: true,
      },
      {
        id: "rev-002",
        userName: "Amina Wanjiku",
        userAvatar: "/user-avatar-2.jpg",
        rating: 4,
        date: "2023-08-22T14:15:00",
        comment:
          "Good experience overall. The center is clean and well-maintained. Only giving 4 stars because the wait time was a bit long during my visit.",
        helpfulCount: 5,
        verifiedVisit: true,
      },
      {
        id: "rev-003",
        userName: "David Ochieng",
        userAvatar: "/user-avatar-3.jpg",
        rating: 5,
        date: "2023-07-10T09:45:00",
        comment:
          "I've been bringing my recyclables here for months and I'm always impressed by their efficiency. They also give tokens that can be redeemed for eco-friendly products!",
        helpfulCount: 8,
        verifiedVisit: true,
        photos: ["/recycling-facility.png"],
      },
    ],
  },
  {
    id: "rc-002",
    name: "GreenCycle Solutions",
    address: "456 Environmental Avenue",
    city: "Nairobi",
    location: { lat: -1.300389, lng: 36.827223 },
    phone: "+254 723 456 789",
    email: "contact@greencycle.co.ke",
    hours: "Mon-Sat: 8am-6pm",
    rating: 4.2,
    distance: 3.7,
    image: "/recycling-center-green-logo.png",
    isPartner: false,
    acceptedMaterials: ["PET", "HDPE", "PVC", "PS"],
    acceptedMaterialsDetails: [
      {
        type: "PET (Polyethylene Terephthalate)",
        code: "Type 1",
        description: "Clear, tough, and solvent resistant. Used for water and soft drink bottles.",
        examples: "Water bottles, soda bottles, cooking oil containers",
      },
      {
        type: "HDPE (High-Density Polyethylene)",
        code: "Type 2",
        description: "Stiff, strong, resistant to chemicals and moisture.",
        examples: "Milk jugs, detergent bottles, shampoo bottles",
      },
      {
        type: "PVC (Polyvinyl Chloride)",
        code: "Type 3",
        description: "Strong, weather resistant, and chemical resistant.",
        examples: "Pipes, shower curtains, window frames, wire insulation",
      },
      {
        type: "PS (Polystyrene)",
        code: "Type 6",
        description: "Rigid, transparent, and insulating.",
        examples: "Disposable cups, food containers, CD cases",
      },
    ],
    preparationGuidelines: [
      "Clean all containers before bringing them in",
      "Sort plastics by type if possible",
      "Remove any non-plastic components",
      "Crush containers to save space",
      "Bring materials in reusable bags or boxes",
    ],
    description:
      "GreenCycle Solutions focuses on innovative approaches to plastic waste management. Our facility uses advanced sorting technology to process various types of plastic waste efficiently.",
    established: "2018",
    capacity: 85,
    facilitySize: 3500,
    collectionRadius: 15,
    satisfactionRate: 88,
    services: [
      "Residential recycling drop-off",
      "Business recycling programs",
      "Plastic upcycling workshops",
      "School recycling education",
      "Recycled product sales",
    ],
    certifications: [
      "ISO 9001 Quality Management",
      "Local Green Business Award",
      "Recycling Industry Operating Standard (RIOS)",
    ],
    directions:
      "From downtown, take Eastern Bypass for 3 km, turn left at Environmental Avenue. We're located in the industrial zone, building with blue roof.",
    reviews: [
      {
        id: "rev-004",
        userName: "Sarah Njeri",
        userAvatar: "/testimonial-avatar-1.jpg",
        rating: 4,
        date: "2023-09-05T11:20:00",
        comment:
          "Convenient location and they accept a wide variety of plastics. Staff could be more helpful with explaining what can and cannot be recycled.",
        helpfulCount: 3,
        verifiedVisit: true,
      },
      {
        id: "rev-005",
        userName: "Michael Mwangi",
        userAvatar: "/testimonial-avatar-2.jpg",
        rating: 5,
        date: "2023-08-12T16:30:00",
        comment:
          "Great place! They have a point system that rewards regular recyclers. I've earned enough points to get a reusable water bottle.",
        helpfulCount: 7,
        verifiedVisit: true,
      },
    ],
  },
  {
    id: "rc-003",
    name: "Circular Plastics Kenya",
    address: "789 Recycling Lane",
    city: "Nairobi",
    location: { lat: -1.276389, lng: 36.807223 },
    phone: "+254 734 567 890",
    email: "info@circularplastics.co.ke",
    hours: "Mon-Fri: 7am-7pm, Sat-Sun: 9am-4pm",
    rating: 4.9,
    distance: 1.5,
    image: "/modern-recycling-facility.png",
    isPartner: true,
    acceptedMaterials: ["PET", "HDPE", "PP", "LDPE", "PS", "Other"],
    acceptedMaterialsDetails: [
      {
        type: "PET (Polyethylene Terephthalate)",
        code: "Type 1",
        description: "Clear, tough, and solvent resistant. Used for water and soft drink bottles.",
        examples: "Water bottles, soda bottles, cooking oil containers",
      },
      {
        type: "HDPE (High-Density Polyethylene)",
        code: "Type 2",
        description: "Stiff, strong, resistant to chemicals and moisture.",
        examples: "Milk jugs, detergent bottles, shampoo bottles",
      },
      {
        type: "PP (Polypropylene)",
        code: "Type 5",
        description: "Strong, heat resistant, and chemical resistant.",
        examples: "Yogurt containers, medicine bottles, bottle caps",
      },
      {
        type: "LDPE (Low-Density Polyethylene)",
        code: "Type 4",
        description: "Flexible, transparent, and moisture resistant.",
        examples: "Plastic bags, squeeze bottles, food packaging film",
      },
      {
        type: "PS (Polystyrene)",
        code: "Type 6",
        description: "Rigid, transparent, and insulating.",
        examples: "Disposable cups, food containers, CD cases",
      },
      {
        type: "Other Plastics",
        code: "Type 7",
        description: "Mixed or layered plastics that don't fit into other categories.",
        examples: "Certain food containers, some medical storage containers",
      },
    ],
    preparationGuidelines: [
      "Rinse all containers to remove food and product residue",
      "Remove all non-plastic parts (metal lids, paper labels)",
      "Separate by plastic type when possible",
      "Flatten containers to reduce volume",
      "Bring in reusable containers or bags",
      "Keep plastic bags separate from hard plastics",
    ],
    description:
      "Circular Plastics Kenya is a leading recycling facility committed to creating a closed-loop system for plastic waste. Our solar-powered facility processes all types of plastic and transforms them into new products, keeping plastic out of landfills and oceans.",
    established: "2016",
    capacity: 200,
    facilitySize: 8000,
    collectionRadius: 30,
    satisfactionRate: 96,
    services: [
      "24/7 drop-off recycling bins",
      "Corporate recycling programs",
      "Mobile collection services",
      "Plastic-to-product manufacturing",
      "Community clean-up events",
      "Recycling education center",
      "Waste audit services",
    ],
    certifications: [
      "ISO 14001 Environmental Management",
      "B Corp Certification",
      "Cradle to Cradle Certified",
      "Zero Waste Facility",
      "Global Recycled Standard (GRS)",
    ],
    directions:
      "Located near the Central Business District. From Uhuru Highway, turn onto Recycling Lane. The facility is at the end of the road with a large sign showing our circular logo.",
    reviews: [
      {
        id: "rev-006",
        userName: "James Kiprop",
        userAvatar: "/testimonial-avatar-3.jpg",
        rating: 5,
        date: "2023-09-20T08:45:00",
        comment:
          "Best recycling center in Nairobi! They accept all types of plastic and their token reward system is fantastic. The staff is knowledgeable and always willing to help.",
        helpfulCount: 15,
        verifiedVisit: true,
        photos: ["/placeholder.svg?height=100&width=100&query=recycling bins"],
      },
      {
        id: "rev-007",
        userName: "Grace Akinyi",
        userAvatar: "/testimonial-avatar-4.jpg",
        rating: 5,
        date: "2023-09-01T13:10:00",
        comment:
          "I love that they're open on weekends and have extended hours. Makes it convenient for working people. Their facility is clean and well-organized.",
        helpfulCount: 9,
        verifiedVisit: true,
      },
      {
        id: "rev-008",
        userName: "Peter Maina",
        userAvatar: "/testimonial-avatar-5.jpg",
        rating: 4,
        date: "2023-08-05T10:30:00",
        comment:
          "Very impressed with their solar-powered facility and commitment to sustainability. They even show you how your plastic gets transformed into new products!",
        helpfulCount: 11,
        verifiedVisit: true,
      },
    ],
  },
  {
    id: "rc-004",
    name: "Community Recyclers",
    address: "321 Green Street",
    city: "Nairobi",
    location: { lat: -1.296389, lng: 36.837223 },
    phone: "+254 745 678 901",
    email: "hello@communityrecyclers.org",
    hours: "Mon-Sat: 9am-5pm",
    rating: 4.0,
    distance: 4.2,
    image: "/placeholder.svg?height=300&width=600&query=community recycling center",
    isPartner: false,
    acceptedMaterials: ["PET", "HDPE"],
    acceptedMaterialsDetails: [
      {
        type: "PET (Polyethylene Terephthalate)",
        code: "Type 1",
        description: "Clear, tough, and solvent resistant. Used for water and soft drink bottles.",
        examples: "Water bottles, soda bottles, cooking oil containers",
      },
      {
        type: "HDPE (High-Density Polyethylene)",
        code: "Type 2",
        description: "Stiff, strong, resistant to chemicals and moisture.",
        examples: "Milk jugs, detergent bottles, shampoo bottles",
      },
    ],
    preparationGuidelines: [
      "Clean all containers before recycling",
      "Remove caps and lids",
      "Flatten bottles to save space",
      "Bring materials in reusable containers",
    ],
    description:
      "Community Recyclers is a grassroots organization focused on making recycling accessible to everyone. We operate as a non-profit and reinvest all proceeds into community environmental projects.",
    established: "2019",
    capacity: 50,
    facilitySize: 1200,
    collectionRadius: 10,
    satisfactionRate: 85,
    services: [
      "Walk-in recycling drop-off",
      "Community education programs",
      "School collection programs",
      "Recycling workshops",
    ],
    certifications: ["Local Environmental Award", "Community Service Recognition"],
    directions:
      "Located in the eastern suburb. Take Green Street past the community center, we're in the yellow building on the right.",
    reviews: [
      {
        id: "rev-009",
        userName: "Lucy Wambui",
        userAvatar: "/user-avatar-3.jpg",
        rating: 4,
        date: "2023-07-25T14:20:00",
        comment:
          "A wonderful community initiative. They're small but doing important work. The volunteers are passionate and helpful.",
        helpfulCount: 6,
        verifiedVisit: true,
      },
      {
        id: "rev-010",
        userName: "Thomas Otieno",
        userAvatar: "/user-avatar-1.jpg",
        rating: 3,
        date: "2023-06-18T11:45:00",
        comment:
          "Good concept but limited in what they accept. Only take PET and HDPE plastics. Hope they expand in the future.",
        helpfulCount: 4,
        verifiedVisit: true,
      },
    ],
  },
  {
    id: "rc-005",
    name: "PlasticBank Kenya",
    address: "567 Ocean Saver Road",
    city: "Mombasa",
    location: { lat: -4.04374, lng: 39.668209 },
    phone: "+254 756 789 012",
    email: "kenya@plasticbank.com",
    hours: "Mon-Fri: 8am-6pm, Sat: 8am-4pm",
    rating: 4.8,
    distance: 485.0,
    image: "/placeholder.svg?height=300&width=600&query=coastal recycling center",
    isPartner: true,
    acceptedMaterials: ["PET", "HDPE", "LDPE", "PP"],
    acceptedMaterialsDetails: [
      {
        type: "PET (Polyethylene Terephthalate)",
        code: "Type 1",
        description: "Clear, tough, and solvent resistant. Used for water and soft drink bottles.",
        examples: "Water bottles, soda bottles, cooking oil containers",
      },
      {
        type: "HDPE (High-Density Polyethylene)",
        code: "Type 2",
        description: "Stiff, strong, resistant to chemicals and moisture.",
        examples: "Milk jugs, detergent bottles, shampoo bottles",
      },
      {
        type: "LDPE (Low-Density Polyethylene)",
        code: "Type 4",
        description: "Flexible, transparent, and moisture resistant.",
        examples: "Plastic bags, squeeze bottles, food packaging film",
      },
      {
        type: "PP (Polypropylene)",
        code: "Type 5",
        description: "Strong, heat resistant, and chemical resistant.",
        examples: "Yogurt containers, medicine bottles, bottle caps",
      },
    ],
    preparationGuidelines: [
      "Rinse all containers to remove residue",
      "Remove all non-plastic components",
      "Sort by plastic type if possible",
      "Bring in clean, dry condition",
      "Collect plastic bags separately",
    ],
    description:
      "PlasticBank Kenya is part of a global movement to stop ocean plastic while improving the lives of collector communities. We operate as a social enterprise that exchanges plastic waste for tokens that can be used for life necessities.",
    established: "2017",
    capacity: 150,
    facilitySize: 6000,
    collectionRadius: 40,
    satisfactionRate: 94,
    services: [
      "Plastic collection for tokens",
      "Ocean plastic prevention",
      "Community empowerment programs",
      "Collector training and equipment",
      "Corporate plastic offset programs",
      "Coastal cleanup initiatives",
    ],
    certifications: [
      "Ocean Bound Plastic Certification",
      "Social Impact Award",
      "Sustainable Development Goals Partner",
      "Fair Trade Practices",
    ],
    directions:
      "Located near the Mombasa port area. Follow Ocean Saver Road until you see our blue and white building with the PlasticBank logo.",
    reviews: [
      {
        id: "rev-011",
        userName: "Omar Hassan",
        userAvatar: "/testimonial-avatar-2.jpg",
        rating: 5,
        date: "2023-09-10T09:15:00",
        comment:
          "Amazing initiative that helps both the environment and local communities. I've been collecting plastic for them for over a year and have seen firsthand the positive impact.",
        helpfulCount: 18,
        verifiedVisit: true,
        photos: ["/placeholder.svg?height=100&width=100&query=plastic collection"],
      },
      {
        id: "rev-012",
        userName: "Fatima Ali",
        userAvatar: "/testimonial-avatar-1.jpg",
        rating: 5,
        date: "2023-08-30T16:40:00",
        comment:
          "Their token system is excellent - I've been able to pay for my children's school supplies by collecting plastic. The staff is respectful and the weighing process is transparent.",
        helpfulCount: 14,
        verifiedVisit: true,
      },
      {
        id: "rev-013",
        userName: "Daniel Kariuki",
        userAvatar: "/user-avatar-2.jpg",
        rating: 4,
        date: "2023-07-15T11:30:00",
        comment:
          "Great concept and execution. The only reason for 4 stars instead of 5 is that sometimes there's a queue during peak hours. Otherwise, highly recommended!",
        helpfulCount: 7,
        verifiedVisit: true,
      },
    ],
  },
]
